# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    cppcheck.yml                                       :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: jaubry-- <jaubry--@student.42lyon.fr>      +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2026/04/16 18:40:05 by jaubry--          #+#    #+#              #
#    Updated: 2026/04/16 18:41:38 by jaubry--         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

name: CI - cppcheck

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  cppcheck:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install cppcheck
        run: sudo apt-get update && sudo apt-get install -y cppcheck

      - name: Run cppcheck
        run: ./.github/scripts/run_cppcheck.sh
